#!/usr/bin/env python3
"""Build the Hermes Base dashboard snapshot from GitHub.

Collects every PR the autoresolver opened on the upstream repo, classifies
closed-but-unmerged PRs (salvaged / superseded / duplicate) from their
comments, and assembles a battle-log feed of recent reviews, comments,
pushes, merges and closures.

Requires an authenticated GitHub CLI (`gh auth status`). Stdlib only.

    python3 refresh_snapshot.py --out snapshot.json

The output is the single document the page reads (`snapshot/latest` in the
artifact's database). Upload it with Claude's ArtifactData tool:
    action=set, collection=snapshot, doc_id=latest, file_path=snapshot.json
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import datetime, timedelta, timezone

SALVAGE_RE = re.compile(r"salvag|cherry-?pick|landed (?:on|in|via)|authorship (?:is )?preserved", re.I)
DUPLICATE_RE = re.compile(r"\bduplicate\b", re.I)
SUPERSEDED_RE = re.compile(r"supersed|already (?:fixed|landed|on main)|fixed on main|redundant", re.I)
FOOTER_RE = re.compile(r"\n-{3,}\s*\n_?Generated by \[Claude Code\].*", re.S)
MAX_DOC_BYTES = 240_000


def gh(path: str, **params) -> object:
    cmd = ["gh", "api", "-X", "GET", path]
    for k, v in params.items():
        cmd += ["-f", f"{k}={v}"]
    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode != 0:
        raise RuntimeError(f"gh api {path} failed: {res.stderr.strip()}")
    return json.loads(res.stdout or "null")


def clean(body: str | None, limit: int = 240) -> str:
    text = FOOTER_RE.sub("", body or "")
    text = re.sub(r"```.*?```", " [code] ", text, flags=re.S)
    text = re.sub(r"<!--.*?-->", " ", text, flags=re.S)
    text = re.sub(r"(^|\s)(?:#{1,6}|>+)\s", " ", text)
    text = re.sub(r"[*`|]+", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text if len(text) <= limit else text[: limit - 1].rsplit(" ", 1)[0] + "…"


def split_title(title: str) -> tuple[str, int | None]:
    m = re.search(r"\s*\(#(\d+)\)\s*$", title)
    return (title[: m.start()] if m else title), (int(m.group(1)) if m else None)


def fetch_prs(repo: str, author: str) -> list[dict]:
    items, page = [], 1
    while True:
        data = gh("search/issues", q=f"author:{author} repo:{repo} is:pr", per_page=100, page=page,
                  sort="created", order="desc")
        items += data["items"]
        if len(data["items"]) < 100 or len(items) >= data["total_count"]:
            return items
        page += 1


def classify(repo: str, author: str, number: int) -> tuple[str | None, str | None, str | None]:
    """Return (closeKind, note, who) for a closed, unmerged PR."""
    for c in reversed(gh(f"repos/{repo}/issues/{number}/comments", per_page=100) or []):
        body = c.get("body") or ""
        who = c["user"]["login"]
        if SALVAGE_RE.search(body):
            return "salvaged", clean(body, 180), who
        if DUPLICATE_RE.search(body):
            return "duplicate", clean(body, 180), who
        if SUPERSEDED_RE.search(body):
            return "superseded", clean(body, 180), who
    return None, None, None


def feed_for(repo: str, author: str, pr: dict, since: str) -> list[dict]:
    n, ev = pr["n"], []
    for c in gh(f"repos/{repo}/issues/{n}/comments", per_page=100) or []:
        if c["created_at"] >= since and (c.get("body") or "").strip():
            ev.append({"at": c["created_at"], "who": c["user"]["login"], "pr": n, "kind": "comment",
                       "text": clean(c["body"])})
    for r in gh(f"repos/{repo}/pulls/{n}/reviews", per_page=100) or []:
        at = r.get("submitted_at") or ""
        if at < since:
            continue
        state = r.get("state")
        if state == "APPROVED":
            ev.append({"at": at, "who": r["user"]["login"], "pr": n, "kind": "approve",
                       "text": clean(r.get("body")) or "Approved."})
        elif (r.get("body") or "").strip():
            ev.append({"at": at, "who": r["user"]["login"], "pr": n, "kind": "review", "text": clean(r["body"])})
    for c in gh(f"repos/{repo}/pulls/{n}/commits", per_page=100) or []:
        at = (c.get("commit") or {}).get("committer", {}).get("date") or ""
        if at >= since:
            msg = (c["commit"].get("message") or "").splitlines()[0]
            ev.append({"at": at, "who": author, "pr": n, "kind": "push", "text": clean(msg, 160)})
    if pr["state"] == "merged" and (pr.get("closed") or "") >= since:
        full = gh(f"repos/{repo}/pulls/{n}")
        who = (full.get("merged_by") or {}).get("login") or "maintainer"
        pr["via"] = who
        ev.append({"at": pr["closed"], "who": who, "pr": n, "kind": "merge", "text": "Merged into main."})
    elif pr["state"] == "closed" and (pr.get("closed") or "") >= since:
        kind = "salvage" if pr.get("closeKind") == "salvaged" else "close"
        ev.append({"at": pr["closed"], "who": pr.get("via") or author, "pr": n, "kind": kind,
                   "text": pr.get("note") or "Closed without merging."})
    return ev


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--repo", default="NousResearch/hermes-agent")
    ap.add_argument("--author", default="PRATHAMESH75")
    ap.add_argument("--days", type=int, default=14, help="battle-log window in days")
    ap.add_argument("--feed-prs", type=int, default=30, help="most recently updated PRs to read threads from")
    ap.add_argument("--classify", type=int, default=80, help="recent closed PRs to classify from comments")
    ap.add_argument("--out", default="snapshot.json")
    args = ap.parse_args()

    raw = fetch_prs(args.repo, args.author)
    prs, updated = [], {}
    for it in raw:
        title, issue = split_title(it["title"])
        merged_at = (it.get("pull_request") or {}).get("merged_at")
        state = "merged" if merged_at else it["state"]
        pr = {"n": it["number"], "title": title, "issue": issue, "state": state,
              "created": it["created_at"], "comments": it.get("comments", 0),
              "labels": [l["name"] for l in it.get("labels", [])]}
        if it.get("closed_at"):
            pr["closed"] = merged_at or it["closed_at"]
        prs.append(pr)
        updated[pr["n"]] = it["updated_at"]

    closed = [p for p in prs if p["state"] == "closed"][: args.classify]
    for p in closed:
        kind, note, who = classify(args.repo, args.author, p["n"])
        if kind:
            p["closeKind"], p["note"], p["via"] = kind, note, who

    since = (datetime.now(timezone.utc) - timedelta(days=args.days)).strftime("%Y-%m-%dT%H:%M:%SZ")
    recent = sorted((p for p in prs if updated[p["n"]] >= since), key=lambda p: updated[p["n"]], reverse=True)
    feed = []
    for p in recent[: args.feed_prs]:
        feed += feed_for(args.repo, args.author, p, since)
    feed.sort(key=lambda e: e["at"], reverse=True)

    snap = {
        "repo": args.repo, "author": args.author,
        "generatedAt": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "source": "GitHub API via gh", "complete": True, "feedPrecision": "exact",
        "totals": {"all": len(prs), "open": sum(p["state"] == "open" for p in prs),
                   "merged": sum(p["state"] == "merged" for p in prs),
                   "closed": sum(p["state"] == "closed" for p in prs)},
        "prs": prs, "feed": feed[:120],
    }
    while len(json.dumps(snap)) > MAX_DOC_BYTES and snap["feed"]:
        snap["feed"] = snap["feed"][: len(snap["feed"]) * 3 // 4]
    with open(args.out, "w") as fh:
        json.dump(snap, fh)
    t = snap["totals"]
    print(f"wrote {args.out}: {t['all']} PRs ({t['open']} open, {t['merged']} merged, {t['closed']} closed), "
          f"{sum(1 for p in prs if p.get('closeKind'))} closures classified, {len(snap['feed'])} feed events")
    return 0


if __name__ == "__main__":
    sys.exit(main())
